name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("devtools", "roxygen2", "testthat", "knitr", "rmarkdown"))'

      - name: Run R CMD check
        run: |
          R CMD build .
          R CMD check JSODPsplines_*.tar.gz